name: Auto PR pre -> main

on:
  push:
    branches: [ pre ]

permissions:
  contents: write
  pull-requests: write

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR exists from pre to main
        id: ensure_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const {owner, repo} = context.repo;
            // Find existing open PR from pre to main
            const prs = await github.paginate(github.rest.pulls.list, {owner, repo, state: 'open', base: 'main', head: `${owner}:pre`});
            if (prs.length > 0) {
              core.setOutput('number', prs[0].number);
              core.setOutput('created', 'false');
              return;
            }
            const title = 'ci: sync pre -> main';
            const body = 'PR automático para integrar cambios de pre en main. Se auto-mergeará cuando los checks pasen (según reglas de protección).';
            const pr = await github.rest.pulls.create({owner, repo, base: 'main', head: 'pre', title, body, maintainer_can_modify: true});
            core.setOutput('number', pr.data.number);
            core.setOutput('created', 'true');

      - name: Enable auto-merge (squash)
        if: ${{ steps.ensure_pr.outputs.number }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.ensure_pr.outputs.number }}
          merge-method: squash