name: Enforce PRs on main

on:
  push:
    branches: [ main ]

jobs:
  no-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Block direct push to main (allow only PR merges)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && !startsWith(github.event.head_commit.message, 'Merge pull request') }}
        run: |
          echo "Direct pushes to main are not allowed. Use pre -> PR -> main." 1>&2
          exit 1