name: Deploy to gh-pages

on:
  push:
  branches: [ main, pre ]
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch, tag or SHA to deploy (defaults to main)"
        required: false
        default: main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # On manual runs, use the requested ref; on push, use the triggering commit
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.ref || github.ref }}
      - name: Add .nojekyll
        run: echo > .nojekyll
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          exclude_assets: |
            .github,docs,*.md,*.yml,*.yaml,CNAME
          force_orphan: true
