name: Deploy Pages (disabled)

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pages deploy disabled; using gh-pages branch via peaceiris/actions-gh-pages"
