name: PR Preview

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add .nojekyll
        run: echo > .nojekyll
      - name: Deploy preview to gh-pages/pr-<num>
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          destination_dir: previews/pr-${{ github.event.number }}
          keep_files: true
          exclude_assets: |
            .github,docs,*.md,*.yml,*.yaml,*.json
      - name: Comment preview URL
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Preview listo:
            - https://aievolutio.com/previews/pr-${{ github.event.number }}/