name: Scheduled link check

on:
  schedule:
    - cron: '0 4 * * 1' # Lunes 04:00 UTC
  workflow_dispatch:

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose .